# compose.yaml
version: '3.8'

services:
 web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

 worker:
    build: .
    command: celery -A app.dependencies.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

 beat:
    build: .
    command: celery -A app.dependencies.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

 redis:
    image: "redis:alpine"
