apiVersion: apps/v1
kind: Deployment
metadata:
 name: fastapi-deployment
 labels:
    app: fastapi
spec:
 replicas: 1
 selector:
    matchLabels:
      app: fastapi
 template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: tbcshopifyhs.azurecr.io/tbc-integration-production-web:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: env-config
